const cartTypes = {
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_CART_ITEM: 'REMOVE_CART_ITEM',
    DECREASE_CART_ITEM_QUANTITY: 'DECREASE_CART_ITEM_QUANTITY',
    CLEAR_CART: 'CLEAR_CART',
};

export default cartTypes;