const categoryTypes = {
    ADD_CATEGORY_START: 'ADD_CATEGORY_START',
    FETCH_CATEGORIES_START: 'FETCH_CATEGORIES_START',
    REMOVE_CATEGORY_START: 'REMOVE_CATEGORY_START',
    SET_CATEGORIES: 'SET_CATEGORIES', 
};

export default categoryTypes;
