const productTypes = {
    ADD_NEW_PRODUCT_START: 'ADD_NEW_PRODUCT_START',
    FETCH_PRODUCTS_START: 'FETCH_PRODUCTS_START',
    DELETE_PRODUCT_START: 'DELETE_PRODUCT_START',
    SET_PRODUCTS: 'SET_PRODUCTS',
};

export default productTypes;